### ISSUE TITLE
How much memory it needs?

### ISSUE THREAD

**Issue by linrio** [nilboy/pixel-recursive-super-resolution#2]
Hi, I want to know this project needs how much memory ? And which type of GPU?

**Comment by nilboy** [comment]
I train on  GeForce GTX 1080.

**Comment by linrio** [comment]
My server is GTX 1070 (8GB VRAM) . How to opti the model?

**Comment by nilboy** [comment]
8GB is enough. maybe you can reduce batch size.

**Comment by linrio** [comment]
ok, thanks!

**Comment by yeqingQian** [comment]
您好，我想问一下您的跑成功了吗？我的总出现错误ImportError: No module named solver

**Comment by nilboy** [comment]
这是python环境的问题，你把当前路径加到pythonpath 下， 
export PYTHONPATH=./:${PYTHONPATH}

**Comment by yeqingQian** [comment]
好的，但是现在出现了新的错误，TypeError: resize_images() takes at least 3 arguments (2 given)，但是给的例子说最后一个参数是可以省略的，而且我把三个参数补全（加0）页是错误的，这个应该怎么解决

**Comment by luckyboysmith** [comment]
@yeqingQian  你好 你的问题解决了吗 我也遇到了问题 能加下QQ一起探讨下吗 我的QQ是2531817472
