### ISSUE TITLE
The code does not work with the new tensorflow versions.

### ISSUE THREAD

**Issue by QLaHPD** [nilboy/pixel-recursive-super-resolution#23]
I tried to follow the requirements (Python 2.7, Skimage, TensorFlow 1.0), but I couldn't install them because I was having a conflict between the packages, so I installed the latest versions, which work until the training crashes.
Would it be possible to update the code to the latest version of TensorFlow, and Python >= 3.0?

**Comment by QGrain** [comment]
Actually you can utilize anaconda to manage your python env, which allows you to create any specific env with different version of python and packages.
