### ISSUE TITLE
problems——solver

### ISSUE THREAD

**Issue by yeqingQian** [nilboy/pixel-recursive-super-resolution#3]
Traceback (most recent call last):
  File "tools/train.py", line 2, in <module>
    from solver import *
ImportError: No module named solver

how to solve?

**Comment by nilboy** [comment]
use python2.7

**Comment by yeqingQian** [comment]
I'm sorry. It can't help.

**Comment by Shimronfio** [comment]
Hi, I have the same issue, maybe we need to arrange the files differently in the data folder?

**Comment by nilboy** [comment]
I have fix the bug , https://github.com/nilboy/pixel-recursive-super-resolution/commit/925d04afb44c035c10f604a7eca02e8f3bc5eb96

**Comment by Shimronfio** [comment]
I got it fixed, 

You need to check your full address where the train.txt is, and write it on the train.py file. 



Hey, Thank you very much for you help and the bug fix,

I have one more little problem when I am trying to run:

I get this messages from python:

*Traceback (most recent call last):*
*File "tools/train.py", line 28, in <module>*
*tf.app.run()*
*File
"/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py",
line 48, in run*
*_sys.exit(main(_sys.argv[:1] + flags_passthrough))*
*File "tools/train.py", line 24, in main*
*solver = Solver()*
*File "./solver.py", line 36, in __init__*
*self.dataset = DataSet(conf.imgs_list_path, self.num_epoch,
self.batch_size)*
*File "./data.py", line 10, in __init__*
*input_file = open(images_list_path, 'r')*
*IOError: [Errno 2] No such file or directory: 'data/train.txt'*

It looks like the file can't be found, is there any mistake on my folder
arrangement? I am sending you the folder screenshot:




unnamed.png
‏
(149K)
<https://mail.google.com/mail/u/0/?ui=2&ik=6628a875da&view=att&th=15d088da63f2e0d2&attid=0.1&disp=safe&realattid=f_j4o5qtkj0&zw>


2017-07-02 15:17 GMT+03:00 nilboy <notifications@github.com>:
