### ISSUE TITLE
AttributeError: 'module' object has no attribute 'losses'

### ISSUE THREAD

**Issue by luckyboysmith** [nilboy/pixel-recursive-super-resolution#6]
thanks for your code!!!!
now when i run python tools/train.py:
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "tools/train.py", line 26, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "tools/train.py", line 22, in main
    solver = Solver()
  File "/home/wangkun/prsr/solver.py", line 37, in __init__
    self.net = Net(self.dataset.hr_images, self.dataset.lr_images, 'prsr')
  File "/home/wangkun/prsr/net.py", line 18, in __init__
    self.construct_net(hr_images, lr_images)
  File "/home/wangkun/prsr/net.py", line 82, in construct_net
    loss1 = self.softmax_loss(self.prior_logits + self.conditioning_logits, labels)
  File "/home/wangkun/prsr/net.py", line 68, in softmax_loss
    return tf.losses.sparse_softmax_cross_entropy(
AttributeError: 'module' object has no attribute 'losses'
[wangkun@mediaszu prsr]$ python tools/train.py
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "tools/train.py", line 26, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "tools/train.py", line 22, in main
    solver = Solver()
  File "/home/wangkun/prsr/solver.py", line 37, in __init__
    self.net = Net(self.dataset.hr_images, self.dataset.lr_images, 'prsr')
  File "/home/wangkun/prsr/net.py", line 18, in __init__
    self.construct_net(hr_images, lr_images)
  File "/home/wangkun/prsr/net.py", line 82, in construct_net
    loss1 = self.softmax_loss(self.prior_logits + self.conditioning_logits, labels)
  File "/home/wangkun/prsr/net.py", line 68, in softmax_loss
    return tf.losses.sparse_softmax_cross_entropy(
AttributeError: 'module' object has no attribute 'losses'

I tried to solve the problem by myself but failed

**Comment by luckyboysmith** [comment]
Before this problem arises，when i run code meets the error:
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

after i solve the TypeError: Expected int32, got list containing Tensors of type '_Message' instead error,
now a new error arise :AttributeError: 'module' object has no attribute 'losses'
I hope you can help me，thanks a lot

**Comment by nilboy** [comment]
tensorflow version is not right. please use tensorflow-1.0

**Comment by luckyboysmith** [comment]
thanks for your reply,i will try
