### ISSUE TITLE
请问训练完成后怎么测试图片？

### ISSUE THREAD

**Issue by luckyboysmith** [nilboy/pixel-recursive-super-resolution#7]
非常感谢你无私提供的代码  在你的帮助下 我的运行遇到的问题已经解决
现在程序正在运行
我想咨询一下 在训练结束后 怎么测试图片？也就是怎么利用一张实际的图片去测试效果
我是新手 不知道自己对问题的描述是否清楚
谢谢！

**Comment by nilboy** [comment]
目前，我还没有提供测试图片的代码，不过你参考solver.py的sample函数，可以很快写出测试代码的

**Comment by luckyboysmith** [comment]
thanks!!!!!

**Comment by wfy93** [comment]
朋友，你有测试代码吗

**Comment by luckyboysmith** [comment]
我还没有写单张测试代码 因为我这边有一些别的优先级较高的事情要做




------------------ 原始邮件 ------------------
发件人: "wfy93";<notifications@github.com>;
发送时间: 2017年5月8日(星期一) 下午4:02
收件人: "nilboy/pixel-recursive-super-resolution"<pixel-recursive-super-resolution@noreply.github.com>; 
抄送: "16-软专-王昆"<2531817472@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [nilboy/pixel-recursive-super-resolution] 请问训练完成后怎么测试图片？ (#7)




朋友，你有测试代码吗

**Comment by luckyboysmith** [comment]
@wfy93

**Comment by wfy93** [comment]
噢噢，我是刚接触这方面的研究生，能不能加个联系方式，非常感谢

**Comment by luckyboysmith** [comment]
2531817472 我和你身份一样额 别抱太大期待




------------------ 原始邮件 ------------------
发件人: "wfy93";<notifications@github.com>;
发送时间: 2017年5月8日(星期一) 下午4:07
收件人: "nilboy/pixel-recursive-super-resolution"<pixel-recursive-super-resolution@noreply.github.com>; 
抄送: "16-软专-王昆"<2531817472@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [nilboy/pixel-recursive-super-resolution] 请问训练完成后怎么测试图片？ (#7)




噢噢，我是刚接触这方面的研究生，能不能加个联系方式，非常感谢

**Comment by luckyboysmith** [comment]
@wfy93

**Comment by geekLR** [comment]
请问您可以把训练好的模型发我一份吗？
