### ISSUE TITLE
求助！

### ISSUE THREAD

**Issue by thisfineday** [nilboy/pixel-recursive-super-resolution#9]
你好，非常感谢你的代码
我在按照您的步骤进行测试时候 我从celebA数据集中 用了17w张图片
迭代了10w次 在3w次后loss基本趋于稳定 可是
我的测试结果不好 眼睛都分不清 面部就是几个方块
 看到您的测试结果 您的结果可谓是眉清目秀我的结果不忍直视  我觉得是我这边的问题（但是我不清楚我该怎么做）
虽然问题很模糊 不过还是希望能得到你的帮助
能给点建议什么的吗 谢谢！

**Comment by thisfineday** [comment]
看到您之前的回答 觉得您应该是华人
我附上一个百度网盘地址 里面是我的测试结果 希望能得到您的帮助！
https://pan.baidu.com/s/1qXZdMaC

**Comment by thisfineday** [comment]
而且loss 最终是在7.8上下浮动

**Comment by nilboy** [comment]
不是很清楚，如果你没有修改代码的话，应该不会出现这种情况的。我当时训练，也没有特意调超参，就达到了这个结果了

**Comment by thisfineday** [comment]
@nilboy  你好 刚才我仔细看了看 我的操作有一步 可能有错误 希望您帮忙看一下
下载的celebA 里面有img_align_celeba和img_celebA
您用的是img_align_celebA吗?
我用的是img_celebA 里面脸部没有对齐，而且除了脸部 大部分图片都是人物全身或者上半身 可能导致我训练差的原因 不知道您用的是哪个(img_celeba还是img_align_celebA)
希望得到您的回复！
提前预祝您五一劳动节快乐！

**Comment by nilboy** [comment]
应该是这个问题， 我用的是img_align_celebA。

**Comment by thisfineday** [comment]
@nilboy   非常感谢你的帮助！
